### PR TITLE
[Add] ESLint

### PR DESCRIPTION
**Pull request by hoangph271**

### CODE REVIEW

**Comment by hoangph271** [comment]
@wood-crafter merge this branch, install [this](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and `npm i`

Fix the issues that `ESLint` yells at you.

**Review by wood-crafter — COMMENTED** [review]
@hoangph271 
This merge have failed all netlify check, please resolve first

**Comment by hoangph271** [comment]
> @hoangph271 This merge have failed all netlify check, please resolve first
@wood-crafter 

- [] Fix the issues that ESLint yells at you.

Looks like you'll have to finish this task before merging...!
Or else Netlify won't build (it doesn't allow ESLint errors)

**Comment by wood-crafter** [comment]
> > @hoangph271 This merge have failed all netlify check, please resolve first
> > @wood-crafter
> 
> * [] Fix the issues that ESLint yells at you.
> 
> Looks like you'll have to finish this task before merging...! Or else Netlify won't build (it doesn't allow ESLint errors)

@hoangph271 
Should i commit this to master

**Comment by hoangph271** [comment]
> > > @hoangph271 This merge have failed all netlify check, please resolve first
> > > @wood-crafter
> > 
> > 
> > 
> > * [] Fix the issues that ESLint yells at you.
> > 
> > Looks like you'll have to finish this task before merging...! Or else Netlify won't build (it doesn't allow ESLint errors)
> 
> @hoangph271 Should i commit this to master

@wood-crafter fix all the issues, push the update to this branch, THEN merge to master

**Comment by hoangph271** [comment]
@wood-crafter screw you, imma fix this

**Pull request merged**
