### PR TITLE
[WIP] draft reduce image loading time

### PR DESCRIPTION
**Pull request by wood-crafter**

### CODE REVIEW

**Comment by hoangph271** [comment]
@wood-crafter I think the code could be better, may be a `queue` for all the dogs...?

**Comment by wood-crafter** [comment]
> @wood-crafter I think the code could be better, may be a `queue` for all the dogs...?
@hoangph271 I dont understand your idea!

**Comment by hoangph271** [comment]
> > @wood-crafter I think the code could be better, may be a `queue` for all the dogs...?
> > @hoangph271 I dont understand your idea!

Okay, I understand that you're using `randomDog1` and `randomDog2` to buffer the API calls, right...?

**Comment by wood-crafter** [comment]
> > > @wood-crafter I think the code could be better, may be a `queue` for all the dogs...?
> > > @hoangph271 I dont understand your idea!
> 
> Okay, I understand that you're using `randomDog1` and `randomDog2` to buffer the API calls, right...?

Yes, should be with diffrent name but i also think there are better wat so using it as draft.
But, Yes

**Comment by hoangph271** [comment]
Maybe, you can create a hook for preloaded dogs, for example:

```jsx
// ? `usePreloadedDogs` is a hook which contains in it a list of preloaded dogs
// when you call `getOneDog`, it will return a dog from `preloadedDogs`
// if this `preloadedDogs` list is empty, the promise will resolve when you fetched a new dog
// `usePreloadedDogs` should have an internal logic to keep `preloadedDogs` from being emptied
const { getOneDog } = usePreloadedDogs()

const nextClickHandler = async () => {
  setRight(mid)
  setMid(left)
  setLeft(await getOneDog())
}
```

**Comment by wood-crafter** [comment]
> Maybe, you can create a hook for preloaded dogs, for example:
> 
> ```js
> // ? `usePreloadedDogs` is a hook which contains in it a list of preloaded dogs
> // when you call `getOneDog`, it will return a dog from `preloadedDogs`
> // if this `preloadedDogs` list is empty, the promise will resolve when you fetched a new dog
> // `usePreloadedDogs` should have an internal logic to keep `preloadedDogs` from being emptied
> const { getOneDog } = usePreloadedDogs()
> 
> const nextClickHandler = async () => {
>   setRight(mid)
>   setMid(left)
>   setLeft(await getOneDog())
> }
> ```

@hoangph271 
The attempt of getting next url doesnt cause much time, but when image loading with getted url, it quite so long.So i tried to load extra image by two none-display image as above.
Do you mean i should setState for randomDog1 and randomDog2 inside usePreloadedDogs?

**Comment by hoangph271** [comment]
@wood-crafter yes, use an array for all the `preloadedDogs`

Btw, when you have a `dogUrl`, you can do this to reduce the load time:

```js
new Image().src = dogUrl
```

**Comment by hoangph271** [comment]
> @wood-crafter yes, use an array for all the `preloadedDogs`
> 
> Btw, when you have a `dogUrl`, you can do this to reduce the load time:
> 
> ```js
> new Image().src = dogUrl
> ```

Next time the image is requested, it will be loaded from memory instead of the network

**Comment by wood-crafter** [comment]
> > @wood-crafter yes, use an array for all the `preloadedDogs`
> > Btw, when you have a `dogUrl`, you can do this to reduce the load time:
> > ```js
> > new Image().src = dogUrl
> > ```
> 
> Next time the image is requested, it will be loaded from memory instead of the network

Where should i put this `new Image().src = dogUrl`? What if i need more than one preload image?

**Comment by hoangph271** [comment]
> > > @wood-crafter yes, use an array for all the `preloadedDogs`
> > > Btw, when you have a `dogUrl`, you can do this to reduce the load time:
> > > ```js
> > > new Image().src = dogUrl
> > > ```
> > 
> > 
> > Next time the image is requested, it will be loaded from memory instead of the network
> 
> Where should i put this `new Image().src = dogUrl`? What if i need more than one preload image?

Anywhere really, maybe as soon as you have the image URL

If you have more than one image, just `new Image().src = url` many times...!

**Comment by wood-crafter** [comment]
> > > > @wood-crafter yes, use an array for all the `preloadedDogs`
> > > > Btw, when you have a `dogUrl`, you can do this to reduce the load time:
> > > > ```js
> > > > new Image().src = dogUrl
> > > > ```
> > > 
> > > 
> > > Next time the image is requested, it will be loaded from memory instead of the network
> > 
> > 
> > Where should i put this `new Image().src = dogUrl`? What if i need more than one preload image?
> 
> Anywhere really, maybe as soon as you have the image URL
> 
> If you have more than one image, just `new Image().src = url` many times...!

Thank you, i will work on it

**Pull request closed without merging**
